[package]
name = "Todo"
version = "0.1.0"
authors = ["Hod04", "Sisi", "mr-lingsteen", "lawelone"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { version = "0.16.2", package = "yew-stdweb" }
