[package]
name = "Todo"
version = "0.1.0"
authors = ["Sisi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.16.2", package = "yew-stdweb" }